configure script was always complaining about OpenAL 1.1

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -397,8 +397,9 @@ sleep(1);
 alcCloseDevice(dev);
 return 0; }"
 test_build "OpenAL 1.1 and ALUT" "$file" "-lopenal -lalut"
-#exit_if_error "$?" "Cannot find OpenAL 1.1 and ALUT. You can try to remove -lalut from Makefile and/or *comp*sh scripts, but Raydium with OpenAL 1.0 is not supported."
-echo "WARNING: Cannot find OpenAL 1.1 and ALUT. You can try to remove -lalut from Makefile and/or *comp*sh scripts, but Raydium with OpenAL 1.0 is not supported."
+if [ $? != 0 ]; then
+    echo "WARNING: Cannot find OpenAL 1.1 and ALUT. You can try to remove -lalut from Makefile and/or *comp*sh scripts, but Raydium with OpenAL 1.0 is not supported."
+fi
 
 # OGG/Vorbis
 file='
